//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudadano1
    {
        public int idciudadano { get; set; }
        public string nombres { get; set; }
        public string nacionalidad { get; set; }
        public string tipodocumento { get; set; }
        public string numdocumento { get; set; }
        public string iddepartamento { get; set; }
        public string idprovincia { get; set; }
        public string iddistrito { get; set; }
        public string idestado { get; set; }
    }
}
